version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tanza-backend
    restart: unless-stopped
    ports:
      - '3030:3030'
      - '3006:3006'
    env_file:
      - .env.production
    volumes:
      - ./uploads:/app/uploads
